# Generated by Django 5.1.1 on 2024-09-12 12:14

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_name', models.CharField(max_length=200)),
                ('rtsp_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('feed_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='FeedPolygon',
            fields=[
                ('polygon_id', models.AutoField(primary_key=True, serialize=False)),
                ('polygon_name', models.CharField(max_length=255)),
                ('polygon', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), size=5)),
                ('polygon_color', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=3)),
                ('feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_app.feed')),
            ],
        ),
    ]
