# Generated by Django 5.1.1 on 2024-10-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventstatus',
            old_name='event_status',
            new_name='status',
        ),
    ]
