# Generated by Django 5.1.1 on 2024-11-01 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonecount',
            name='count_type',
            field=models.CharField(default='in', max_length=5),
        ),
        migrations.AlterField(
            model_name='feedpolygon',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_polygons', to='config_app.feed'),
        ),
    ]
