# Generated by Django 5.1.1 on 2024-10-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('event_status', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedpolygon',
            name='feed',
        ),
        migrations.AddField(
            model_name='feedpolygon',
            name='feeds',
            field=models.ManyToManyField(related_name='feed_polygons', to='config_app.feed'),
        ),
    ]
