# Generated by Django 5.1.1 on 2024-11-01 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0002_zonecount_count_type_alter_feedpolygon_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatus',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_app.event'),
        ),
    ]
