# Generated by Django 5.1.1 on 2024-11-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0003_alter_eventstatus_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventstatus',
            old_name='event_id',
            new_name='event',
        ),
        migrations.CreateModel(
            name='FeedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_app.feed')),
            ],
        ),
    ]
